//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatYouEatWP7.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhatYouEatWP7.Resources.Common.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you eat?.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of birthday.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eaten.
        /// </summary>
        public static string Eaten {
            get {
                return ResourceManager.GetString("Eaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eanten for today.
        /// </summary>
        public static string EatenForToday {
            get {
                return ResourceManager.GetString("EatenForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eat food.
        /// </summary>
        public static string EatFood {
            get {
                return ResourceManager.GetString("EatFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glass.
        /// </summary>
        public static string Glass {
            get {
                return ResourceManager.GetString("Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gramm.
        /// </summary>
        public static string Gramm {
            get {
                return ResourceManager.GetString("Gramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how much were eaten.
        /// </summary>
        public static string HowMuchEaten {
            get {
                return ResourceManager.GetString("HowMuchEaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input your data..
        /// </summary>
        public static string InputYourData {
            get {
                return ResourceManager.GetString("InputYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keep my weight.
        /// </summary>
        public static string KeepWeight {
            get {
                return ResourceManager.GetString("KeepWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string Kilo {
            get {
                return ResourceManager.GetString("Kilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lose.
        /// </summary>
        public static string LoseWeight {
            get {
                return ResourceManager.GetString("LoseWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my goal.
        /// </summary>
        public static string MyGoal {
            get {
                return ResourceManager.GetString("MyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to portion.
        /// </summary>
        public static string Portion {
            get {
                return ResourceManager.GetString("Portion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to put on.
        /// </summary>
        public static string PutOnWeight {
            get {
                return ResourceManager.GetString("PutOnWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spent.
        /// </summary>
        public static string Spent {
            get {
                return ResourceManager.GetString("Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total eaten.
        /// </summary>
        public static string TotalEaten {
            get {
                return ResourceManager.GetString("TotalEaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to.
        /// </summary>
        public static string WantTo {
            get {
                return ResourceManager.GetString("WantTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
